
operation_points:
  - fluid_name: air
    T0_in: 295.6
    p0_in: 13.8e4
    p_out: [13.8e4/2.298] #, 13.8e4/2.5]
    omega: 1627
    alpha_in: 0

  - fluid_name: air
    T0_in: 295.6
    p0_in: 13.8e4
    p_out: [13.8e4/2.298] #, 13.8e4/2.5]
    omega: 1627
    alpha_in: 0

performance_map:
  fluid_name: air
  T0_in: 295.6
  p0_in: 13.8e4
  p_out: 13.8e4/np.linspace(1.5, 4.5, 10)
  omega: [1627]
  alpha_in: 0

model_options:
  _slip_model: glassman
  choking_condition : deviation
  deviation_model : aungier
  blockage_model : 0.0 #flat_plate_turbulent
  rel_step_fd: 1e-3
  loss_model:
    model: benner
    loss_coefficient: stagnation_pressure
    inlet_displacement_thickness_height_ratio: 0.011
    tuning_factors:
      profile: 1.00
      incidence: 1.00
      secondary: 1.00
      trailing: 1.00
      clearance: 1.00

solver_options:
  method: hybr
  tolerance: 1e-8
  max_iterations: 100
  derivative_method: "2-point"
  derivative_rel_step: 1e-4
  display_progress: True




geometry:
  cascade_type: ["stator", "rotor"]
  radius_hub: [0.084785, 0.084785, 0.084785, 0.08185]
  radius_tip: [0.118415, 0.118415, 0.118415, 0.12135]
  pitch: [1.8294e-2, 1.524e-2]
  chord: [2.616e-2, 2.606e-2]
  stagger_angle: [+43.03, -31.05]
  opening: [0.7731e-2, 0.7249e-2]
  diameter_le: [2*0.127e-2, 2*0.081e-2]
  wedge_angle_le: [50.00, 50.00]
  metal_angle_le: [0.00, 29.60]
  metal_angle_te: [65.00, -61.60]
  thickness_te: [0.050e-2, 0.050e-2]
  thickness_max: [0.505e-2, 0.447e-2]
  tip_clearance: [0.00, 0.030e-2]
  throat_location_fraction: [1.0, 1.0]
  # throat_location_fraction: [5/6, 5/6]


_geometry_optimization:
  radius_type: constant_mean_radius
  cascade_type: ["stator", "rotor"]
  camberline_type: ['circular_arc', 'circular_arc']
  hub_tip_ratio: [0.80, 0.80, 0.80, 0.80]
  pitch_chord_ratio: [0.75, 0.75]
  aspect_ratio: [2.00, 2.00]
  thickness_te_opening_ratio: [0.05, 0.05] 
  wedge_angle_le: [45.0, 45.0]
  metal_angle_le: [0.00, 0.00]
  metal_angle_te: [60, -60]
  thickness_max_chord_ratio: [0.20, 0.20]
  tip_clearance_height_ratio: [0.01, 0.01]
  diameter_le_chord_ratio: [0.15, 0.15]
  throat_location_fraction: [1.00, 1.00]
