operation_points:
  fluid_name: air
  T0_in: 295.6
  p0_in: 13.8e4
  p_out: 13.8e4/2.298
  omega: 1627
  alpha_in: 0

performance_map:
  fluid_name: air
  T0_in: 295.6
  p0_in: 13.8e4
  p_out: 13.8e4/np.linspace(1.5, 4.5, 50)
  omega: [1627]
  alpha_in: 0

model_options:
  loss_model: benner  # Loss model (Benner only for off-design, KO only other option)
  displacement_thickness : 0
  deviation_model : aungier
  choking_condition : deviation

solver_options:
  method: hybr
  tolerance: 1e-9
  max_iterations: 50
  derivative_method: "2-point"
  derivative_rel_step: 1e-4
  display_progress: True



geometry:
  cascade_type: ["stator", "rotor"]
  radius_hub: [0.084785, 0.084785, 0.084785, 0.08185]
  radius_tip: [0.118415, 0.118415, 0.118415, 0.12135]
  pitch: [1.8294e-2, 1.524e-2]
  chord: [2.616e-2, 2.606e-2]
  stagger_angle: [+43.03, -31.05]
  opening: [0.7731e-2, 0.7249e-2]
  diameter_le: [2*0.127e-2, 2*0.081e-2]
  wedge_angle_le: [50.00, 50.00]
  metal_angle_le: [0.00, 29.60]
  metal_angle_te: [65.00, -61.60]
  thickness_te: [0.050e-2, 0.050e-2]
  thickness_max: [0.505e-2, 0.447e-2]
  tip_clearance: [0.00, 0.030e-2]
  throat_location_fraction: [1, 1]
  # throat_location_fraction: [5/6, 5/6]





# geometry_optimization:
#   radius_specification: constant_mean
#   hub_tip_ratio: [0.9, 0.9, 0.9, 0.9]
#   metal_angle_leading: []
#   metal_angle_trailing: []
#   aspect_ratio: []
#   pitch_to_chord_ratio: []
#   thickness_max_to_chord_ratio: []
#   trailing_edge_to_opening_ratio:  []
#   throat_to_exit_opening_ratio: []


# optimization:
#   fixed_parameters:
#     - wedge_angle
#     - thickness_max

#   design_variables:
#     pitch_to_chord:
#       lower_bound: 
#       upper_bound: 
#       initial_guess:

#   constraints:
#     flaring_angle:
#       lower_bound: [-15, -12]
#       upper_bound: +15

#     flaring_angle: [-15, +15]
#     flaring_angle: +15

#     hub_to_tip_ratio:
#       upper_bound: 0.95
#       lower_bound: [0.9, 0.85, 0.8, 0.7]

#     degree_of_reaction: 0.5
#       # target: 0.5






# Computed variables
# Number of blades
# Radius mean
# Flow areas
# Axial chord/stagger
# 

  # Add option to give chord/stagger or axialChord/stagger or chord/axialChord
  # Add option to give single value for radius for constant radius
  # Add option to give single value for hub_tip_ratio for cylindrical turbine