turbomachinery: axial_turbine
operation_points: 
  fluid_name: air          # Fluid
  T0_in: 295.6             # Inlet total temperature
  p0_in: 13.8e4            # Inlet total pressure
  p_out : 13.8e4/2.298     # Exit static pressure
  omega: 1627              # Rotational speed
  alpha_in: 0              # Flow angle at first stator


simulation_options: 
  deviation_model : aungier 
  choking_criterion : critical_mach_number
  # rel_step_fd: 1e-4 
  loss_model:  
    model: benner
    loss_coefficient: stagnation_pressure  
    inlet_displacement_thickness_height_ratio: 0.011  
  
performance_analysis :
  performance_map: 
    fluid_name: air 
    T0_in: 295.6
    p0_in: 13.8e4
    p_out: 13.8e4/np.linspace(1.6, 4.5, 40)
    omega: 1627 
    alpha_in: 0 
  solver_options:
    method: lm 
    tolerance: 1e-8  
    max_iterations: 100 
    derivative_method: 2-point  
    derivative_abs_step: 1e-6 
    print_convergence: True
    plot_convergence: False
  initial_guess :
      efficiency_tt : [0.9, 0.8] 
      efficiency_ke : [0.2, 0.1]
      ma_1 : [0.8, 0.8]
      ma_2 : [0.8, 0.8]

geometry:
  cascade_type: ["stator", "rotor"]
  radius_hub_in: [0.084785, 0.084785]
  radius_hub_out: [0.084785, 0.081875]
  radius_tip_in: [0.118415, 0.118415]
  radius_tip_out: [0.118415, 0.121325]
  pitch: [1.8294e-2, 1.524e-2]
  chord: [2.616e-2, 2.606e-2]
  stagger_angle: [+43.03, -31.05]
  opening: [0.747503242e-2, 0.735223377e-2]
  leading_edge_angle : [0.00, 29.60]
  leading_edge_wedge_angle : [50.00, 50.00]
  leading_edge_diameter : [2*0.127e-2, 2*0.081e-2]
  trailing_edge_thickness : [0.050e-2, 0.050e-2]
  maximum_thickness : [0.505e-2, 0.447e-2]
  tip_clearance: [0.00, 0.030e-2]
  throat_location_fraction: [1, 1] # Should be changed
  

design_optimization:
  objective_function:
    variable : overall.efficiency_ts
    scale : 1
    type : maximize
  variables :
    specific_speed : # Limited
      value : 0.713756
      lower_bound : 0.5
      upper_bound : 1.5
    blade_jet_ratio : # Limited
      value : 0.466501
      lower_bound : 0.3
      upper_bound : 0.8
    hub_tip_ratio_in :
      value : [0.715999, 0.715999]
      lower_bound : [0.6, 0.6]
      upper_bound : [0.9, 0.9]
    hub_tip_ratio_out :
      value : [0.715999, 0.674840]
      lower_bound : [0.6, 0.6]
      upper_bound : [0.9, 0.9]
    aspect_ratio :
      value : [1.285550, 1.402149]
      lower_bound : [1.0, 1.0]
      upper_bound : [2.0, 2.0]
    pitch_chord_ratio :
      value : [0.699312, 0.584804]
      lower_bound : [0.5, 0.5]
      upper_bound : [1.10, 1.10]
    trailing_edge_thickness_opening_ratio :
      value : [0.066889, 0.068007]
      lower_bound : [0.05, 0.05]
      upper_bound : [0.2, 0.2]
    leading_edge_angle : # (-70-15)
      value : [0.5, 0.66444444]
      lower_bound : [0.11111111, 0.41666667]
      upper_bound : [0.58333333, 0.88888889]
    gauging_angle : # (55-75)
      value : [0.86601513, 0.16024573]
      lower_bound : [0.80555556, 0.08333333]
      upper_bound : [0.91666667, 0.19444444]
    v_in :
      value : 0.22715060950254562
      lower_bound : 0.001
      upper_bound : 0.5
    w_out :
      value : [0.7560168311370046, 0.714178597145251]
      lower_bound : [0.1, 0.1]
      upper_bound : [1.0, 1.0]
    s_out :
      value : [0.02393594702543656, 0.07236629937075202]
      lower_bound : [0.0, 0.0]
      upper_bound : [0.32, 0.32]
    beta_out :
      value : [0.8650417242559838, 0.16150395974996423]
      lower_bound : [0.72, 0.06]
      upper_bound : [0.94, 0.28]
    w_crit_throat :
      value : [0.954641310153918, 0.8901549785503726]
      lower_bound : [0.1, 0.1]
      upper_bound : [1.0, 1.0]
    s_crit_throat :
      value : [0.04006361313218885, 0.09614205881131721]
      lower_bound : [0.0, 0.0]
      upper_bound : [0.32, 0.32]
    throat_location_fraction :
      value : [5/6, 5/6]
    leading_edge_diameter :
      value : [2*0.127e-2, 2*0.081e-2]
    leading_edge_wedge_angle :
      value : [50.0, 50.0]
    tip_clearance :
      value : [0.00, 0.030e-2]
    cascade_type :
      value : ["stator", "rotor"]
  constraints : # Optional
    - variable: overall.mass_flow_rate
      type : "="
      value : 2.721057
      normalize : True
    - variable : additional_constraints.interspace_area_ratio
      type : "="
      value : 1
      normalize : True
    - variable : geometry.flaring_angle
      type : "<"
      value : 10
      normalize : True
    - variable : geometry.flaring_angle
      type : ">"
      value : -10
      normalize : True

  radius_type : "constant_mean"
  
  solver_options:
    # library: pygmo
    # method: ipopt
    # library: scipy
    # method: slsqp
    # derivative_method: 2-point
    # derivative_method: jax
    # derivative_abs_step: 1e-9
    print_convergence: True
    plot_convergence: False
    update_on: "gradient"
    # tolerance: 1e-8
    # max_iterations: 1e3
    extra_options: {}




