name: meanline_env
#channels:
#  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - numpy
    - scipy
    - matplotlib
    - pandas
    - coolprop
    - openpyxl
    - pyyaml
    - parse
    - black
    - ipython
    - pexpect
    - cycler
    - sphinx
    - sphinx-tabs
    - sphinx-book-theme
    - sphinx-rtd-theme
    - pydata-sphinx-theme
    - numpydoc
    - sphinxcontrib-bibtex
    - pyzotero
    - pytest
    - sphinxawesome-theme
    - sphinx-design
    - imageio

