cycle_topology: recuperated
plot_settings:
  pinch_point_diagram: true
  fluid:
    plot_saturation_line: true
    plot_critical_point: true
    plot_quality_isolines: true
    plot_pseudocritical_line: false
    plot_triple_point_liquid: false
    plot_triple_point_vapor: false
  diagrams:
  - x_variable: s
    y_variable: T
    x_scale: linear
    y_scale: linear
fixed_parameters:
  working_fluid:
    name: butane
    backend: HEOS
    exceptions: false
  heating_fluid:
    name: water
    backend: HEOS
    exceptions: true
  cooling_fluid:
    name: water
    backend: HEOS
    exceptions: true
  net_power: 1
  heat_source:
    inlet_temperature: 393.15
    exit_temperature_max: 393.15
    exit_temperature_min: 293.15
    inlet_pressure: 1013250
    exit_pressure: 1013250
  heat_sink:
    inlet_temperature: 293.15
    exit_temperature_min: 298.15
    exit_temperature_max: 303.15
    inlet_pressure: 101325
    exit_pressure: 101325
  heater:
    pressure_drop_hot_side: 0.01
    pressure_drop_cold_side: 0.01
    num_elements: 50
  recuperator:
    pressure_drop_hot_side: 0.01
    pressure_drop_cold_side: 0.01
    num_elements: 25
  cooler:
    pressure_drop_hot_side: 0.01
    pressure_drop_cold_side: 0.01
    num_elements: 50
  turbine:
    efficiency: 0.9
    efficiency_type: isentropic
  compressor:
    efficiency: 0.8
    efficiency_type: isentropic
  heat_source_pump:
    efficiency: 0.8
    efficiency_type: isentropic
  heat_sink_pump:
    efficiency: 0.8
    efficiency_type: isentropic
design_variables:
  heat_source_exit_temperature:
    min: $heat_source.exit_temperature_min
    max: $heat_source.exit_temperature_max
    value: 0.1
  heat_sink_exit_temperature:
    min: $heat_sink.exit_temperature_min
    max: $heat_sink.exit_temperature_max
    value: 0.5
  compressor_inlet_pressure:
    min: 0.9*$cycle_fluid.liquid_at_heat_sink_temperature.p
    max: 2.5*$cycle_fluid.liquid_at_heat_sink_temperature.p
    value: 0.5
  compressor_inlet_enthalpy:
    min: 0.9*$cycle_fluid.liquid_at_heat_sink_temperature.h
    max: 1.5*$cycle_fluid.liquid_at_heat_sink_temperature.h
    value: 0.2
  turbine_inlet_pressure:
    min: 0.9*$cycle_fluid.liquid_at_heat_sink_temperature.p
    max: 1.5*$cycle_fluid.critical_point.p
    value: 0.5
  turbine_inlet_enthalpy:
    min: 0.20*$cycle_fluid.gas_at_heat_source_temperature.h
    max: 1.00*$cycle_fluid.gas_at_heat_source_temperature.h
    value: 0.5
  recuperator_effectiveness:
    min: 0.0
    max: 0.0
    value: 0.0
constraints:
- variable: $components.heater.temperature_difference
  type: '>'
  value: 5
  normalize: true
- variable: $components.cooler.temperature_difference
  type: '>'
  value: 5
  normalize: true
- variable: $components.turbine.state_in.Q
  type: '>'
  value: 1.0
- variable: $components.compressor.state_in.subcooling
  type: '>'
  value: 1
  normalize: true
objective_function:
  variable: $energy_analysis.system_efficiency
  type: maximize
