turbomachinery: axial_turbine
simulation_options: # Optional
  deviation_model : zero_deviation  # Optional
  # blockage_model : 0.00  #flat_plate_turbulent  # Optional
  choking_model : evaluate_cascade_critical # evaluate_cascade_critical, evaluate_cascade_throat, evaluate_cascade_isentropic_throat  # Optional
  # rel_step_fd: 1e-4  # Optional
  loss_model:  # Optional
    model: kacker_okapuu  # Optional
    loss_coefficient: stagnation_pressure  # Optional
    # inlet_displacement_thickness_height_ratio: 0.011  # Optional
    # tuning_factors:  # Optional
      # profile: 1.00  # Optional
      # incidence: 1.00  # Optional
      # secondary: 1.00  # Optional
      # trailing: 1.00  # Optional
      # clearance: 1.00  # Optional

geometry:
  cascade_type: ["stator", "rotor"]
  radius_hub_in: [0.084785, 0.084785]
  radius_hub_out: [0.084785, 0.081875]
  radius_tip_in: [0.118415, 0.118415]
  radius_tip_out: [0.118415, 0.121325]
  pitch: [1.8294e-2, 1.524e-2]
  chord: [2.616e-2, 2.606e-2]
  stagger_angle: [+43.03, -31.05]
  opening: [0.747503242e-2, 0.735223377e-2]
  leading_edge_angle : [0.00, 29.60]
  leading_edge_wedge_angle : [50.00, 50.00]
  leading_edge_diameter : [2*0.127e-2, 2*0.081e-2]
  trailing_edge_thickness : [0.050e-2, 0.050e-2]
  maximum_thickness : [0.505e-2, 0.447e-2]
  tip_clearance: [0.00, 0.030e-2]
  throat_location_fraction: [1, 1]

operation_points: 
  fluid_name: air
  T0_in: 295.6
  p0_in: 13.8e4
  p_out : 13.8e4/2.298 #, 13.8e4/2.5]
  omega: 1627
  alpha_in: 0

performance_analysis:
  performance_map: # Optional
    fluid_name: air 
    T0_in: 295.6
    p0_in: 13.8e4
    p_out: 13.8e4/np.linspace(2.3, 2.4, 2)
    omega: 1627 
    alpha_in: 0 
  
  solver_options: # Optional
    method: hybr  # Optional
    tolerance: 1e-8  # Optional
    max_iterations: 100  # Optional
    derivative_method: "2-point"  # Optional
    derivative_abs_step: 1e-6  # Optional
    print_convergence: True
    plot_convergence: True

design_optimization:
  objective_function: efficiency_ts # Optional
  variables :
    specific_speed :
      value : 1.2
      lower_bound : 0.01
      upper_bound : 10
    blade_jet_ratio :
      value : 0.5
      lower_bound : 0.1
      upper_bound : 0.9
    hub_tip_ratio_in :
      value : [0.6, 0.6]
      lower_bound : [0.6, 0.6]
      upper_bound : [0.9, 0.9]
    hub_tip_ratio_out :
      value : [0.6, 0.6]
      lower_bound : [0.6, 0.6]
      upper_bound : [0.9, 0.9]
    aspect_ratio :
      value : [1.5, 1.5]
      lower_bound : [1.0, 1.0]
      upper_bound : [2.0, 2.0]
    pitch_chord_ratio :
      value : [0.9, 0.9]
      lower_bound : [0.75, 0.75]
      upper_bound : [1.10, 1.10]
    trailing_edge_thickness_opening_ratio :
      value : [0.1, 0.1]
      lower_bound : [0.05, 0.05]
      upper_bound : [0.4, 0.4]
    leading_edge_angle :
      value : [0.41, 0.5]
      lower_bound : [0.41, 0.08]
      upper_bound : [0.92, 0.58]
    gauging_angle :
      value : [0.17, 0.94]
      lower_bound : [0.06, 0.72]
      upper_bound : [0.28, 0.94]
    v_in :
      value : 0.1
      lower_bound : 0.001
      upper_bound : 0.5
    w_out : 
      value : [0.65, 0.65]
      lower_bound : [0.1, 0.1]
      upper_bound : [1.0, 1.0]
    s_out : 
      value : [0.15, 0.15]
      lower_bound : [0.0, 0.0]
      upper_bound : [0.32, 0.32]
    beta_out : 
      value : [0.83, 0.17]
      lower_bound : [0.72, 0.06]
      upper_bound : [0.94, 0.28]
    v*_in : 
      value : [0.4, 0.4]
      lower_bound : [0.1, 0.1]
      upper_bound : [1.0, 1.0]
    beta*_throat : 
      value : [0.83, 0.17]
      lower_bound : [0.72, 0.06]
      upper_bound : [0.94, 0.28]
    w*_throat : 
      value : [0.65, 0.65]
      lower_bound : [0.1, 0.1]
      upper_bound : [1.0, 1.0]
    s*_throat : 
      value : [0.15, 0.15]
      lower_bound : [0.0, 0.0]
      upper_bound : [0.32, 0.32]
    throat_location_fraction : 
      value : [1.0, 1.0]
    leading_edge_diameter :
      value : [2*0.127e-2, 2*0.081e-2]
    leading_edge_wedge_angle :
      value : [50.0, 50.0]
    tip_clearance :
      value : [0.00, 0.030e-2]
    cascade_type : 
      value : ["stator", "rotor"]
  constraints : # Optional
    mass_flow_rate :
      type : "="
      value : 2.5
      normalize : True 
    interstage_flaring :
      type : "="
      value : 1
      normalize : True
  radius_type : "constant_mean" # Optional
  solver_options: # Optional
    library: pygmo # Optional
    method: ipopt # Optional
    tolerance: 1e-3 # Optional
    max_iterations: 100 # Optional
    derivative_method: 2-point # Optional
    derivative_abs_step: 1e-6 # Optional
    print_convergence: True # Optional
    plot_convergence: True # Optional
    update_on: "gradient" # Optional
  
  

