
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # or whichever version you are using

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.8'  # or whichever version you are using

    - name: Create conda environment
      run: conda env create -f environment.yml

    - name: Activate conda environment
      run: source activate myenv  # replace 'myenv' with the name of your environment as specified in environment.yml

    - name: Install dependencies
      run: conda install --file requirements.txt  # if you have a requirements.txt file, otherwise skip this step

    - name: Run tests
      run: |
        source activate myenv
        pytest  