
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # or whichever version you are using

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.11'  # or whichever version you are using

    - name: Create conda environment
      run: |
        conda env create -f environment.yml

    - name: Activate conda environment
      run: |
        source "$(conda info --base)/etc/profile.d/conda.sh"
        conda activate turboflow_env
        pip install --upgrade pip
        pip install -e .

    - name: Run tests
      run: |
        source "$(conda info --base)/etc/profile.d/conda.sh"
        conda activate turboflow_env
        pytest
        
  test_windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # or whichever version you are using

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.11'  # or whichever version you are using

    - name: Create conda environment
      run: conda env create -f environment.yml

    - name: Activate conda environment and install dependencies
      run: |
        conda activate turboflow_env
        pip install --upgrade pip
        pip install -e .
      shell: bash -l {0}

    - name: Run tests
      run: |
        conda activate turboflow_env
        pytest
      shell: bash -l {0}